version: "3.2"
services:
  db:
    container_name: "db"
    image: "postgres:13"
    ports:
      - "2345:5432"
    environment:
      POSTGRES_PASSWORD: "martinez"
      POSTGRES_DB: "algoserio"
    volumes:
      - db-data:/var/lib/postgresql/data:z
    restart: always

  adminer:
    container_name: "adminer"
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  db-data:
    name: db-data
